version: '3.8'

services:

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
