version: '3.8'

services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.3
    ports:
      - 2181:2181
  
  kafka:
    image: quay.io/debezium/kafka:2.3
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    restart: 'on-failure'
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      BROKER_ID: 1

  kafka_connect:
    image: quay.io/debezium/connect:2.3
    ports:
      - 8083:8083
    depends_on:
      - kafka
    restart: 'on-failure'
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    